### ISSUE TITLE
Cards returned from QueryBuilder have different column name

### ISSUE THREAD

**Issue by danielguardicore** [mertsalik/metabasepy#18]
When querying a card and parsing the resulting table Metabasepy expects the following items under the data field of the query response

data_requirements = {
            'columns',
            'rows',
            'native_form'
        }

However, the resulting data contains 'cols' and not 'columns'.

**Comment by mertsalik** [comment]
On which version of Metabase you are experiencing this ?

**Comment by zdk123** [comment]
I'm seeing this too.  Metabase v0.35.3

**Comment by mertsalik** [comment]
Should be fixed with #1.8.0
https://github.com/mertsalik/metabasepy/releases/tag/1.8.0
