### ISSUE TITLE
Wow - nice stackoverflow trap

### ISSUE THREAD

**Issue by pPanda-beta** [mertsalik/metabasepy#23]
You can not do infinite self recursion like this, please call super endpoint. 

https://github.com/mertsalik/metabasepy/blob/3b6c5f37d3ed8151f6fdbbb6614ac5c02b9089f9/metabasepy/client.py#L302-L303

**Comment by mertsalik** [comment]
fixed with new release 
https://github.com/mertsalik/metabasepy/releases/tag/1.7.0

thanks again.
