### ISSUE TITLE
get_by_collection not working

### ISSUE THREAD

**Issue by Ruben170** [mertsalik/metabasepy#24]
I don't seem to be able to get this working:
`collection = cli.collections.get(collection_id=7)
questions = cli.cards.get_by_collection(collection_slug=collection["slug"])`

or when I do it like this:

`questions = cli.cards.get_by_collection('collection_name)`

it always returns the Our Analytics collection

**Comment by mertsalik** [comment]
Can you try this and write your outputs here ?

`
from metabasepy import Client

cli = Client(username="your_username", password="do_not_share_your_pass", base_url="https://metabase.foobar.com")

cli.authenticate()

cli.collections.get()
`
this should list all available collections for you, and then check your collection id again.

may be you didn't call the `authenticate` methode before trying to access these services ?

**Comment by Ruben170** [comment]
When I use cli.collections.get() it does give me all my collections. However getting a specific collection by id doesn't work for me. Using a workaround now that does work.

**Comment by mertsalik** [comment]
Hmm, i can't seem to reproduce this bug 😞 


<img width="580" alt="Screen Shot 2020-10-09 at 02 07 19" src="https://user-images.githubusercontent.com/652489/95522312-71174800-09d4-11eb-8178-373b5b884031.png">

<img width="574" alt="Screen Shot 2020-10-09 at 02 12 15" src="https://user-images.githubusercontent.com/652489/95522479-e84cdc00-09d4-11eb-83af-1a0f74ad8d12.png">
