### ISSUE TITLE
Client.collections.get()---metabasepy.client.RequestException

### ISSUE THREAD

**Issue by liumin19920802** [mertsalik/metabasepy#35]
![image](https://user-images.githubusercontent.com/59193854/150141121-b0d04389-1d0f-4d91-a965-17f21417f62e.png)

**Comment by mertsalik** [comment]
Hi @liumin19920802 , how exactly did you get this error ?

**Comment by liumin19920802** [comment]
![image](https://user-images.githubusercontent.com/59193854/150241325-3263cd01-4868-4404-b876-c06a6287c8ed.png)

**Comment by mertsalik** [comment]
Hi @liumin19920802 ,

you have to authenticate first, than you'll access api resources.

```
from metabasepy import Client

cli = Client(
    username="USERNAME",
    password="PASSW0RD",
    base_url="https://foo-bar.domain.com"
)

cli.authenticate()
all_dbs = cli.databases.get()
print(all_dbs)
```

cli.authenticate() is the missing step on your code.
