### ISSUE TITLE
Misplaced trailing comma

### ISSUE THREAD

**Issue by kauto23** [mertsalik/metabasepy#38]
The trailing comma on this line needs removing. It's creating the verify attribute as a tuple (True, ) rather than simply a boolean, which is resulting in an error when using any method related to ApiCommand.

https://github.com/mertsalik/metabasepy/blob/2bed2590e02c1ee5ab8bf25ee94570092fcb531f/metabasepy/client.py#L96

Thanks a lot

**Comment by mertsalik** [comment]
![image](https://user-images.githubusercontent.com/652489/162987603-2ffb0cf5-8c3d-41f6-afc1-f1cad22e4626.png)

Hi @kauto23 this should have be fixed with v1.12 release, 
Can you please update your package and check ?

Thanks
